import { createSlice } from "@reduxjs/toolkit"

const initialState = {
  voters:  [
  {
    voterId: "V001",
    fullName: "Amit Sharma",
    firstName: "Amit",
    lastName: "Sharma",
    relativeName: "Rajesh Sharma",
    houseNo: "21B",
    addressLine1: "Laxmi Nagar",
    addressLine2: "East Delhi",
    gender: "Male",
    age: 34,
    mobileNumber: "9876543210",
    caste: "General",
    sectionDetails: "Section A",
    yadiNumber: "Y001",
    assemblyConstituencyNumber: 101,
    assemblyConstituencyName: "East Delhi",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 7,
    lokSabhaConstituencyName: "Delhi",
    lokSabhaReservationStatus: "General",
    hometown: "Delhi",
    policeStation: "Preet Vihar",
    taluka: "Shahdara",
    district: "East Delhi",
    pinCode: "110092",
  },
  {
    voterId: "V002",
    fullName: "Sita Reddy",
    firstName: "Sita",
    lastName: "Reddy",
    relativeName: "Krishna Reddy",
    houseNo: "102",
    addressLine1: "Madhapur",
    addressLine2: "HiTech City",
    gender: "Female",
    age: 29,
    mobileNumber: "9001234567",
    caste: "OBC",
    sectionDetails: "Section B",
    yadiNumber: "Y002",
    assemblyConstituencyNumber: 123,
    assemblyConstituencyName: "Serilingampally",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 9,
    lokSabhaConstituencyName: "Hyderabad",
    lokSabhaReservationStatus: "General",
    hometown: "Hyderabad",
    policeStation: "Jubilee Hills",
    taluka: "Serilingampally",
    district: "Rangareddy",
    pinCode: "500081",
  },
  {
    voterId: "V003",
    fullName: "Rahul Yadav",
    firstName: "Rahul",
    lastName: "Yadav",
    relativeName: "Vinod Yadav",
    houseNo: "55A",
    addressLine1: "Ashok Nagar",
    addressLine2: "Kanpur",
    gender: "Male",
    age: 42,
    mobileNumber: "8887654321",
    caste: "OBC",
    sectionDetails: "Section C",
    yadiNumber: "Y003",
    assemblyConstituencyNumber: 202,
    assemblyConstituencyName: "Govind Nagar",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 4,
    lokSabhaConstituencyName: "Kanpur",
    lokSabhaReservationStatus: "General",
    hometown: "Kanpur",
    policeStation: "Govind Nagar PS",
    taluka: "Kanpur",
    district: "Kanpur Nagar",
    pinCode: "208006",
  },
  {
    voterId: "V004",
    fullName: "Priya Desai",
    firstName: "Priya",
    lastName: "Desai",
    relativeName: "Kiran Desai",
    houseNo: "11C",
    addressLine1: "Ellis Bridge",
    addressLine2: "Ahmedabad",
    gender: "Female",
    age: 31,
    mobileNumber: "7894561230",
    caste: "General",
    sectionDetails: "Section A",
    yadiNumber: "Y004",
    assemblyConstituencyNumber: 145,
    assemblyConstituencyName: "Ellisbridge",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 6,
    lokSabhaConstituencyName: "Ahmedabad West",
    lokSabhaReservationStatus: "SC",
    hometown: "Ahmedabad",
    policeStation: "Ellis Bridge",
    taluka: "Ahmedabad",
    district: "Ahmedabad",
    pinCode: "380006",
  },
  {
    voterId: "V005",
    fullName: "Arjun Verma",
    firstName: "Arjun",
    lastName: "Verma",
    relativeName: "Mahesh Verma",
    houseNo: "48D",
    addressLine1: "Vijay Nagar",
    addressLine2: "Indore",
    gender: "Male",
    age: 38,
    mobileNumber: "9123456780",
    caste: "SC",
    sectionDetails: "Section D",
    yadiNumber: "Y005",
    assemblyConstituencyNumber: 200,
    assemblyConstituencyName: "Indore-3",
    assemblyReservationStatus: "SC",
    lokSabhaConstituencyNumber: 12,
    lokSabhaConstituencyName: "Indore",
    lokSabhaReservationStatus: "General",
    hometown: "Indore",
    policeStation: "MG Road PS",
    taluka: "Indore",
    district: "Indore",
    pinCode: "452001",
  },
  {
    voterId: "V006",
    fullName: "Meena Kumari",
    firstName: "Meena",
    lastName: "Kumari",
    relativeName: "Ramesh Kumari",
    houseNo: "C-89",
    addressLine1: "Sector 12",
    addressLine2: "Noida",
    gender: "Female",
    age: 27,
    mobileNumber: "9999999999",
    caste: "SC",
    sectionDetails: "Section E",
    yadiNumber: "Y006",
    assemblyConstituencyNumber: 125,
    assemblyConstituencyName: "Noida",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 10,
    lokSabhaConstituencyName: "Gautam Buddha Nagar",
    lokSabhaReservationStatus: "General",
    hometown: "Noida",
    policeStation: "Sector 20 PS",
    taluka: "Dadri",
    district: "Gautam Buddha Nagar",
    pinCode: "201301",
  },
    {
    voterId: "V007",
    fullName: "Rohit Patil",
    firstName: "Rohit",
    lastName: "Patil",
    relativeName: "Suresh Patil",
    houseNo: "12A",
    addressLine1: "Shivaji Nagar",
    addressLine2: "Pune",
    gender: "Male",
    age: 40,
    mobileNumber: "9812345678",
    caste: "OBC",
    sectionDetails: "Section B",
    yadiNumber: "Y007",
    assemblyConstituencyNumber: 150,
    assemblyConstituencyName: "Shivajinagar",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 14,
    lokSabhaConstituencyName: "Pune",
    lokSabhaReservationStatus: "General",
    hometown: "Pune",
    policeStation: "Shivaji Nagar PS",
    taluka: "Pune City",
    district: "Pune",
    pinCode: "411005",
  },
  {
    voterId: "V008",
    fullName: "Laxmi Devi",
    firstName: "Laxmi",
    lastName: "Devi",
    relativeName: "Bansi Lal",
    houseNo: "5D",
    addressLine1: "Chandni Chowk",
    addressLine2: "Old Delhi",
    gender: "Female",
    age: 65,
    mobileNumber: "9823456781",
    caste: "General",
    sectionDetails: "Section F",
    yadiNumber: "Y008",
    assemblyConstituencyNumber: 102,
    assemblyConstituencyName: "Chandni Chowk",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 8,
    lokSabhaConstituencyName: "Delhi",
    lokSabhaReservationStatus: "General",
    hometown: "Delhi",
    policeStation: "Kotwali PS",
    taluka: "Central Delhi",
    district: "Central Delhi",
    pinCode: "110006",
  },
  {
    voterId: "V009",
    fullName: "Karan Singh",
    firstName: "Karan",
    lastName: "Singh",
    relativeName: "Bhupinder Singh",
    houseNo: "101",
    addressLine1: "Model Town",
    addressLine2: "Ludhiana",
    gender: "Male",
    age: 36,
    mobileNumber: "9834567890",
    caste: "General",
    sectionDetails: "Section G",
    yadiNumber: "Y009",
    assemblyConstituencyNumber: 217,
    assemblyConstituencyName: "Ludhiana North",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 13,
    lokSabhaConstituencyName: "Ludhiana",
    lokSabhaReservationStatus: "General",
    hometown: "Ludhiana",
    policeStation: "Model Town PS",
    taluka: "Ludhiana",
    district: "Ludhiana",
    pinCode: "141002",
  },
  {
    voterId: "V010",
    fullName: "Sunita Mehta",
    firstName: "Sunita",
    lastName: "Mehta",
    relativeName: "Ravi Mehta",
    houseNo: "77",
    addressLine1: "Boring Road",
    addressLine2: "Patna",
    gender: "Female",
    age: 45,
    mobileNumber: "9876501234",
    caste: "General",
    sectionDetails: "Section H",
    yadiNumber: "Y010",
    assemblyConstituencyNumber: 180,
    assemblyConstituencyName: "Bankipur",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 15,
    lokSabhaConstituencyName: "Patna Sahib",
    lokSabhaReservationStatus: "General",
    hometown: "Patna",
    policeStation: "Boring Road PS",
    taluka: "Patna Sadar",
    district: "Patna",
    pinCode: "800001",
  },
  {
    voterId: "V011",
    fullName: "Anil Kumar",
    firstName: "Anil",
    lastName: "Kumar",
    relativeName: "Ram Kumar",
    houseNo: "33",
    addressLine1: "Kankarbagh",
    addressLine2: "Patna",
    gender: "Male",
    age: 32,
    mobileNumber: "9700011223",
    caste: "SC",
    sectionDetails: "Section I",
    yadiNumber: "Y011",
    assemblyConstituencyNumber: 181,
    assemblyConstituencyName: "Patna Central",
    assemblyReservationStatus: "SC",
    lokSabhaConstituencyNumber: 15,
    lokSabhaConstituencyName: "Patna Sahib",
    lokSabhaReservationStatus: "General",
    hometown: "Patna",
    policeStation: "Kankarbagh PS",
    taluka: "Patna Sadar",
    district: "Patna",
    pinCode: "800020",
  },
  {
    voterId: "V012",
    fullName: "Radha Nair",
    firstName: "Radha",
    lastName: "Nair",
    relativeName: "Suresh Nair",
    houseNo: "9B",
    addressLine1: "Kalamassery",
    addressLine2: "Ernakulam",
    gender: "Female",
    age: 50,
    mobileNumber: "9898989898",
    caste: "General",
    sectionDetails: "Section J",
    yadiNumber: "Y012",
    assemblyConstituencyNumber: 83,
    assemblyConstituencyName: "Kalamassery",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 16,
    lokSabhaConstituencyName: "Ernakulam",
    lokSabhaReservationStatus: "General",
    hometown: "Ernakulam",
    policeStation: "Kalamassery PS",
    taluka: "Paravur",
    district: "Ernakulam",
    pinCode: "683104",
  },
  {
    voterId: "V013",
    fullName: "Deepak Joshi",
    firstName: "Deepak",
    lastName: "Joshi",
    relativeName: "Harish Joshi",
    houseNo: "88",
    addressLine1: "Raopura",
    addressLine2: "Vadodara",
    gender: "Male",
    age: 41,
    mobileNumber: "9845612345",
    caste: "General",
    sectionDetails: "Section K",
    yadiNumber: "Y013",
    assemblyConstituencyNumber: 141,
    assemblyConstituencyName: "Raopura",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 17,
    lokSabhaConstituencyName: "Vadodara",
    lokSabhaReservationStatus: "General",
    hometown: "Vadodara",
    policeStation: "Raopura PS",
    taluka: "Vadodara",
    district: "Vadodara",
    pinCode: "390001",
  },
  {
    voterId: "V014",
    fullName: "Ananya Roy",
    firstName: "Ananya",
    lastName: "Roy",
    relativeName: "Tapas Roy",
    houseNo: "4/1",
    addressLine1: "Salt Lake",
    addressLine2: "Kolkata",
    gender: "Female",
    age: 30,
    mobileNumber: "9776654321",
    caste: "General",
    sectionDetails: "Section L",
    yadiNumber: "Y014",
    assemblyConstituencyNumber: 169,
    assemblyConstituencyName: "Bidhannagar",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 18,
    lokSabhaConstituencyName: "Kolkata North",
    lokSabhaReservationStatus: "General",
    hometown: "Kolkata",
    policeStation: "Bidhannagar PS",
    taluka: "North 24 Parganas",
    district: "Kolkata",
    pinCode: "700064",
  },
    {
    voterId: "V015",
    fullName: "Vikram Chauhan",
    firstName: "Vikram",
    lastName: "Chauhan",
    relativeName: "Pratap Chauhan",
    houseNo: "17C",
    addressLine1: "Civil Lines",
    addressLine2: "Allahabad",
    gender: "Male",
    age: 39,
    mobileNumber: "9811122233",
    caste: "General",
    sectionDetails: "Section M",
    yadiNumber: "Y015",
    assemblyConstituencyNumber: 256,
    assemblyConstituencyName: "Allahabad North",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 19,
    lokSabhaConstituencyName: "Prayagraj",
    lokSabhaReservationStatus: "General",
    hometown: "Allahabad",
    policeStation: "Civil Lines PS",
    taluka: "Allahabad",
    district: "Prayagraj",
    pinCode: "211001",
  },
  {
    voterId: "V016",
    fullName: "Neha Kapoor",
    firstName: "Neha",
    lastName: "Kapoor",
    relativeName: "Ravi Kapoor",
    houseNo: "44B",
    addressLine1: "MG Road",
    addressLine2: "Bengaluru",
    gender: "Female",
    age: 28,
    mobileNumber: "9745567890",
    caste: "General",
    sectionDetails: "Section N",
    yadiNumber: "Y016",
    assemblyConstituencyNumber: 170,
    assemblyConstituencyName: "Shivajinagar",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 20,
    lokSabhaConstituencyName: "Bangalore Central",
    lokSabhaReservationStatus: "General",
    hometown: "Bengaluru",
    policeStation: "Shivajinagar PS",
    taluka: "Bangalore North",
    district: "Bangalore Urban",
    pinCode: "560001",
  },
  {
    voterId: "V017",
    fullName: "Sandeep Mishra",
    firstName: "Sandeep",
    lastName: "Mishra",
    relativeName: "Hari Mishra",
    houseNo: "76A",
    addressLine1: "Hazratganj",
    addressLine2: "Lucknow",
    gender: "Male",
    age: 46,
    mobileNumber: "9630011122",
    caste: "General",
    sectionDetails: "Section O",
    yadiNumber: "Y017",
    assemblyConstituencyNumber: 173,
    assemblyConstituencyName: "Lucknow Central",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 21,
    lokSabhaConstituencyName: "Lucknow",
    lokSabhaReservationStatus: "General",
    hometown: "Lucknow",
    policeStation: "Hazratganj PS",
    taluka: "Lucknow",
    district: "Lucknow",
    pinCode: "226001",
  },
  {
    voterId: "V018",
    fullName: "Divya Rani",
    firstName: "Divya",
    lastName: "Rani",
    relativeName: "Shyam Rani",
    houseNo: "99",
    addressLine1: "Rajendra Nagar",
    addressLine2: "Indore",
    gender: "Female",
    age: 33,
    mobileNumber: "9923456789",
    caste: "OBC",
    sectionDetails: "Section P",
    yadiNumber: "Y018",
    assemblyConstituencyNumber: 201,
    assemblyConstituencyName: "Indore-4",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 12,
    lokSabhaConstituencyName: "Indore",
    lokSabhaReservationStatus: "General",
    hometown: "Indore",
    policeStation: "Rajendra Nagar PS",
    taluka: "Indore",
    district: "Indore",
    pinCode: "452012",
  },
  {
    voterId: "V019",
    fullName: "Mohammed Irfan",
    firstName: "Mohammed",
    lastName: "Irfan",
    relativeName: "Nasir Khan",
    houseNo: "12/4",
    addressLine1: "Charminar",
    addressLine2: "Hyderabad",
    gender: "Male",
    age: 44,
    mobileNumber: "9876512345",
    caste: "OBC",
    sectionDetails: "Section Q",
    yadiNumber: "Y019",
    assemblyConstituencyNumber: 60,
    assemblyConstituencyName: "Charminar",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 9,
    lokSabhaConstituencyName: "Hyderabad",
    lokSabhaReservationStatus: "General",
    hometown: "Hyderabad",
    policeStation: "Charminar PS",
    taluka: "Hyderabad",
    district: "Hyderabad",
    pinCode: "500002",
  },
  {
    voterId: "V020",
    fullName: "Rekha Yadav",
    firstName: "Rekha",
    lastName: "Yadav",
    relativeName: "Dinesh Yadav",
    houseNo: "27E",
    addressLine1: "Gomti Nagar",
    addressLine2: "Lucknow",
    gender: "Female",
    age: 36,
    mobileNumber: "9767894321",
    caste: "OBC",
    sectionDetails: "Section R",
    yadiNumber: "Y020",
    assemblyConstituencyNumber: 174,
    assemblyConstituencyName: "Lucknow East",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 21,
    lokSabhaConstituencyName: "Lucknow",
    lokSabhaReservationStatus: "General",
    hometown: "Lucknow",
    policeStation: "Gomti Nagar PS",
    taluka: "Lucknow",
    district: "Lucknow",
    pinCode: "226010",
  },
  {
    voterId: "V021",
    fullName: "Tarun Singh",
    firstName: "Tarun",
    lastName: "Singh",
    relativeName: "Narendra Singh",
    houseNo: "15/3",
    addressLine1: "Raja Park",
    addressLine2: "Jaipur",
    gender: "Male",
    age: 29,
    mobileNumber: "9786543210",
    caste: "General",
    sectionDetails: "Section S",
    yadiNumber: "Y021",
    assemblyConstituencyNumber: 142,
    assemblyConstituencyName: "Adarsh Nagar",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 22,
    lokSabhaConstituencyName: "Jaipur",
    lokSabhaReservationStatus: "General",
    hometown: "Jaipur",
    policeStation: "Raja Park PS",
    taluka: "Jaipur",
    district: "Jaipur",
    pinCode: "302004",
  },
     {
    voterId: "V022",
    fullName: "Nikita Sharma",
    firstName: "Nikita",
    lastName: "Sharma",
    relativeName: "Ajay Sharma",
    houseNo: "45C",
    addressLine1: "Sector 22",
    addressLine2: "Chandigarh",
    gender: "Female",
    age: 27,
    mobileNumber: "9811198765",
    caste: "General",
    sectionDetails: "Section T",
    yadiNumber: "Y022",
    assemblyConstituencyNumber: 1,
    assemblyConstituencyName: "Chandigarh",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 1,
    lokSabhaConstituencyName: "Chandigarh",
    lokSabhaReservationStatus: "General",
    hometown: "Chandigarh",
    policeStation: "Sector 22 PS",
    taluka: "Chandigarh",
    district: "Chandigarh",
    pinCode: "160022",
  },
  {
    voterId: "V023",
    fullName: "Rahul Verma",
    firstName: "Rahul",
    lastName: "Verma",
    relativeName: "Manoj Verma",
    houseNo: "18A",
    addressLine1: "Nirala Nagar",
    addressLine2: "Kanpur",
    gender: "Male",
    age: 34,
    mobileNumber: "9822200112",
    caste: "OBC",
    sectionDetails: "Section U",
    yadiNumber: "Y023",
    assemblyConstituencyNumber: 217,
    assemblyConstituencyName: "Govind Nagar",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 23,
    lokSabhaConstituencyName: "Kanpur",
    lokSabhaReservationStatus: "General",
    hometown: "Kanpur",
    policeStation: "Govind Nagar PS",
    taluka: "Kanpur",
    district: "Kanpur Nagar",
    pinCode: "208006",
  },
  {
    voterId: "V024",
    fullName: "Pooja Bhatt",
    firstName: "Pooja",
    lastName: "Bhatt",
    relativeName: "Mahesh Bhatt",
    houseNo: "11",
    addressLine1: "Colaba",
    addressLine2: "Mumbai",
    gender: "Female",
    age: 38,
    mobileNumber: "9833001122",
    caste: "General",
    sectionDetails: "Section V",
    yadiNumber: "Y024",
    assemblyConstituencyNumber: 175,
    assemblyConstituencyName: "Colaba",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 26,
    lokSabhaConstituencyName: "Mumbai South",
    lokSabhaReservationStatus: "General",
    hometown: "Mumbai",
    policeStation: "Colaba PS",
    taluka: "Mumbai",
    district: "Mumbai",
    pinCode: "400005",
  },
  {
    voterId: "V025",
    fullName: "Manoj Das",
    firstName: "Manoj",
    lastName: "Das",
    relativeName: "Satyam Das",
    houseNo: "9C",
    addressLine1: "Khandagiri",
    addressLine2: "Bhubaneswar",
    gender: "Male",
    age: 42,
    mobileNumber: "9776654433",
    caste: "General",
    sectionDetails: "Section W",
    yadiNumber: "Y025",
    assemblyConstituencyNumber: 118,
    assemblyConstituencyName: "Bhubaneswar",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 17,
    lokSabhaConstituencyName: "Bhubaneswar",
    lokSabhaReservationStatus: "General",
    hometown: "Bhubaneswar",
    policeStation: "Khandagiri PS",
    taluka: "Bhubaneswar",
    district: "Khordha",
    pinCode: "751030",
  },
  {
    voterId: "V026",
    fullName: "Sneha Desai",
    firstName: "Sneha",
    lastName: "Desai",
    relativeName: "Ramesh Desai",
    houseNo: "55A",
    addressLine1: "Navrangpura",
    addressLine2: "Ahmedabad",
    gender: "Female",
    age: 31,
    mobileNumber: "9911223344",
    caste: "General",
    sectionDetails: "Section X",
    yadiNumber: "Y026",
    assemblyConstituencyNumber: 63,
    assemblyConstituencyName: "Ellisbridge",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 9,
    lokSabhaConstituencyName: "Ahmedabad West",
    lokSabhaReservationStatus: "SC",
    hometown: "Ahmedabad",
    policeStation: "Navrangpura PS",
    taluka: "Ahmedabad City",
    district: "Ahmedabad",
    pinCode: "380009",
  },
  {
    voterId: "V027",
    fullName: "Amitabh Tripathi",
    firstName: "Amitabh",
    lastName: "Tripathi",
    relativeName: "Sharad Tripathi",
    houseNo: "21",
    addressLine1: "Civil Lines",
    addressLine2: "Gorakhpur",
    gender: "Male",
    age: 47,
    mobileNumber: "9780011223",
    caste: "General",
    sectionDetails: "Section Y",
    yadiNumber: "Y027",
    assemblyConstituencyNumber: 322,
    assemblyConstituencyName: "Gorakhpur Urban",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 64,
    lokSabhaConstituencyName: "Gorakhpur",
    lokSabhaReservationStatus: "General",
    hometown: "Gorakhpur",
    policeStation: "Civil Lines PS",
    taluka: "Gorakhpur",
    district: "Gorakhpur",
    pinCode: "273001",
  },
  {
    voterId: "V028",
    fullName: "Bhavna Rawat",
    firstName: "Bhavna",
    lastName: "Rawat",
    relativeName: "Ravindra Rawat",
    houseNo: "8B",
    addressLine1: "Rajpur Road",
    addressLine2: "Dehradun",
    gender: "Female",
    age: 35,
    mobileNumber: "9765432100",
    caste: "General",
    sectionDetails: "Section Z",
    yadiNumber: "Y028",
    assemblyConstituencyNumber: 19,
    assemblyConstituencyName: "Dehradun Cantonment",
    assemblyReservationStatus: "General",
    lokSabhaConstituencyNumber: 5,
    lokSabhaConstituencyName: "Tehri Garhwal",
    lokSabhaReservationStatus: "General",
    hometown: "Dehradun",
    policeStation: "Rajpur Road PS",
    taluka: "Dehradun",
    district: "Dehradun",
    pinCode: "248001",
  }

  

],
  filteredVoters: [],
  currentPage: 1,
  itemsPerPage: 25,
  searchTerm: "",
  filters: {
    gender: "",
    age: "",
    caste: "",
    district: "",
    taluka: "",
  },
  selectedVoter: null,
  loading: false,
  error: null,
}

const votersSlice = createSlice({
  name: "voters",
  initialState,
  reducers: {
    setVoters: (state, action) => {
      state.voters = action.payload
      state.filteredVoters = action.payload
    },
    addVoter: (state, action) => {
      state.voters.push(action.payload)
      state.filteredVoters.push(action.payload)
    },
    updateVoter: (state, action) => {
      const index = state.voters.findIndex((voter) => voter.voterId === action.payload.voterId)
      if (index !== -1) {
        state.voters[index] = action.payload
        state.filteredVoters[index] = action.payload
      }
    },
    deleteVoter: (state, action) => {
      state.voters = state.voters.filter((voter) => voter.voterId !== action.payload)
      state.filteredVoters = state.filteredVoters.filter((voter) => voter.voterId !== action.payload)
    },
    setSearchTerm: (state, action) => {
      state.searchTerm = action.payload
      state.currentPage = 1
    },
    setFilters: (state, action) => {
      state.filters = { ...state.filters, ...action.payload }
      state.currentPage = 1
    },
    setCurrentPage: (state, action) => {
      state.currentPage = action.payload
    },
    setSelectedVoter: (state, action) => {
      state.selectedVoter = action.payload
    },
    applyFilters: (state) => {
      let filtered = state.voters

      if (state.searchTerm) {
        filtered = filtered.filter(
          (voter) =>
            voter.fullName.toLowerCase().includes(state.searchTerm.toLowerCase()) ||
            voter.voterId.toLowerCase().includes(state.searchTerm.toLowerCase()),
        )
      }

      Object.keys(state.filters).forEach((key) => {
        if (state.filters[key]) {
          filtered = filtered.filter(
            (voter) => voter[key] && voter[key].toString().toLowerCase().includes(state.filters[key].toLowerCase()),
          )
        }
      })

      state.filteredVoters = filtered
    },
    setLoading: (state, action) => {
      state.loading = action.payload
    },
    setError: (state, action) => {
      state.error = action.payload
    },
  },
})

export const {
  setVoters,
  addVoter,
  updateVoter,
  deleteVoter,
  setSearchTerm,
  setFilters,
  setCurrentPage,
  setSelectedVoter,
  applyFilters,
  setLoading,
  setError,
} = votersSlice.actions

export default votersSlice.reducer
